### ISSUE TITLE
BUG: "Open Output Folder" does not open the output folder

### ISSUE THREAD

**Issue by Kani3D** [symunona/obsidian-bulk-exporter#10]
Hello,

i discovered a small bug where clicking the "Open Output Folder" won't open the output folder.
I'm using the latest version of obsidian (1.6.3) and your plugin (2.011), OS Windows 11.

Other plugins are using the format to access the local browser: `file:///C:\Windows\System32`

**Comment by symunona** [comment]
Thanks for the detailed description, I would have missed that it's on windows... So now it should be working! (took me a while to hook up a windows machine hence the setback.)
