### ISSUE TITLE
FR: Add an option the preview the bulk export

### ISSUE THREAD

**Issue by Kani3D** [symunona/obsidian-bulk-exporter#11]
Hello,

i'd find it convenient to have another option to preview the bulk export first before directly running it, so we can use the **awesome** Preview feature to adjust/check it.

There could be two available options:
Bulk Exporter: Bulk Export
Bulk Exporter: Preview Export

![image](https://github.com/symunona/obsidian-bulk-exporter/assets/105086349/d777de1c-5df6-45c4-9bae-eb49a86494d1)

**Comment by symunona** [comment]
Great idea! Just released it on 2.0.12!

Caveats: it only works after export was done.
Just click the front of the exported file to bring up the stats of the file:
![image](https://github.com/symunona/obsidian-bulk-exporter/assets/5897104/1aa4c0ec-ecb2-42a2-8e1f-fbdc6576ac31)
