### ISSUE TITLE
markdown links in obsidian properties

### ISSUE THREAD

**Issue by tbleiker** [symunona/obsidian-bulk-exporter#5]
Markdown links do not seem to work properly in Obsidian properties. 

E.g. if you have a note called "Note" with the following Obsidian properties:

```
---
links:
  - "[First Note](First Note)"
  - "[Second Note](Second Note)"
---
```

The notes "First Note" and "Second Note" do not recognize "Note" as linked mentions. This is a shortcoming of Obsidian. I hope this will get fixed soon. 

Meanwhile keeping wiki links instead of replacing them with markdown links might be an intermediate solution.

**Comment by symunona** [comment]
This is because there are spaces in them. 

With 2.0.6 I just tested with wiki links that's a workaround.

Please confirm!

**Comment by tbleiker** [comment]
Works. Thx!
