### ISSUE TITLE
backslash in image linke does not work

### ISSUE THREAD

**Issue by tbleiker** [symunona/obsidian-bulk-exporter#6]
When replacing the wiki link for assets with a markdown link, your plugin adds blackslashes for the file path. This does not work for me (Obsidian on Windows). Replacing them with forward slahes fixes this.

**Comment by symunona** [comment]
Should be fixed for windows, please confirm!

**Comment by tbleiker** [comment]
Now, I get an "InternalAttachmentsError: ***.jpg - Asset not found!" for all attachments.

**Comment by tbleiker** [comment]
When I add the attachment folder to the wiki link (`![[Attachments/image.png]]`), the slash seems to get replaced by `%2F` and I get "Attachments%2Fimage.png - Asset not found".

**Comment by symunona** [comment]
Indeed. Sorry about this, I never used wikilink styled MD before, I will add these to my tests too eventually. 
This is supposed to be fixed in version 2.0.8, please confirm!
