### ISSUE TITLE
Option to retain links to non-exported notes

### ISSUE THREAD

**Issue by joelg** [symunona/obsidian-bulk-exporter#7]
Hi @symunona - thank you for this incredible plugin. I love the level of control it provides with dataview queries and string literals for the export structure.

Could you consider adding an option to retain links to non-exported notes? i.e. not remove those links.

_Context: I am exporting in separate batches with your feature to create exports for different subsets of notes, and sometimes there's a linked note in a separate subset that then gets removed. I am essentially using separate subsets to allow for different queries and folder structures, and then I combine it all back up for my personal website. Unfortunately I'm losing some links currently with the way this plugin work. Having an option to retain the links would solve this for me._

Thanks!

**Comment by symunona** [comment]
Hi @joelg!

Thanks for using the plugin! 

I created two new flags under links and attachment settings on  [#2.0.9](https://github.com/symunona/obsidian-bulk-exporter/releases/tag/2.0.9) 
- one to keep the private ones, and 
- one to keep the simply not found ones (it can be useful for adding custom links to e.g. headers)

I hope this solves your problem!

**Comment by joelg** [comment]
Wow, this is perfect and that was very fast! Thanks @symunona!
