### ISSUE TITLE
BUG: Preserve Wikilinks does not work and assets are beeing renamed

### ISSUE THREAD

**Issue by Kani3D** [symunona/obsidian-bulk-exporter#9]
Hello,

thanks for your effort on this plugin. It feels great to use but i'm encountering two bugs.

I'm using this plugin to automate the export of my notes to quartz.
I got the latest versions and also tried it in the sandbox vault.

1. Even if toggled my wikilinks` ![[Attachmentname]]` will be converted to` ![Attachmentname](filename)`
![image](https://github.com/symunona/obsidian-bulk-exporter/assets/105086349/2b1a7485-0d87-4586-9007-77e4e6bf5e8c)

2. Exported attachments are beeing renamed like this: embeds-20230911-1`-f85b7806944b41dc002aef57a84c7922`.pdf which makes them not work in quartz.
![image](https://github.com/symunona/obsidian-bulk-exporter/assets/105086349/7cea93bb-f8f8-4d85-be74-1b2fa1d6bde5)

Please let me know if i can provide further information.

Thanks in advance.

**Comment by symunona** [comment]
Hi! Thanks for using the plugin!

I dug a little of what it could possibly be the cause, and I found a few things in the process:
- I have added a toggle, you can now switch off the renaming of the file. Originally it's there if you have 10 different `image.png` files, and you do not want to accidentally overwrite them when reorganizing the structure, you'll have a separate instance based on it's content (that's an MD5 hash at the back), but I am not sure if that it your problem...
- An actual BUG I found - that you mentioned - is that the attachment links did always transform to the `[]()` notation and ignored the "preserve wiki links" toggle. I fixed this, now they, will be preserved, and I do believe this will solve your problem.
- I noticed that you are embedding the links, and this lead me to discover another bug: when I was just linking attachments, attachments do not have metadata, so they never were considered "public" - so if you have just a link to e.g. `[[assets/something.pdf]]` - it would have NOT have been copied. 
I considered this to be fixed, so now, I properly copy over links that point to an "image style" embed file, like PDF, JPG, etc - not only if it's embedded. If your links were not working, I believe this might have been a reason. This however may break/fix some people's worklflow, although yours is the first report, and before it probably would have just skipped it all together.

Anyways, let me know if this fixes your problem, I have addressed it in [2.0.11](https://github.com/symunona/obsidian-bulk-exporter/releases/tag/2.0.11)
Please mark this done if it fixed your problem!

**Comment by Kani3D** [comment]
I really appreciate the fast response and thank you for the insights of how your plugin is meant to work.
I immediately started testing the new version.

- The toggle does work and will no longer rename the files. By importing/embedding the files to obsidian they'll already get a unique name in my workflow. (using [Paste-Image-Rename-Plugin](https://github.com/reorx/obsidian-paste-image-rename))
- In fact the toggle does work as intended now. However it will add the filepath before/within the link.
Origin in obsidian: `![[Embeds-20230911-1.pdf]]` 
After export `with preserve wiki links toggle on`: `![[Attachments/Embeds-20230911-1.pdf|Embeds-20230911-1.pdf]]`

If there was an option the toggle between filepath beeing included or not that would be awesome.
To make the export flawlessly work to the `quartz\content` folder the filelink must stay `![[Embeds-20230911-1.pdf]]`.
Quartz will automatically find the corresponding attachments inside the content folder.

- I can confirm this works now. All attachments are beeing exported.

**Comment by symunona** [comment]
I created a new toggle for this use case: it's "Leave wiki links as is", that should solve your problem I believe!

I was a little afraid that it's the wrong abstraction, have been thinking about it for a while, but could not come up with a cleaner solution than the toggle.
